In [99]:
import math
import numpy as np

In [85]:
def warmup(length, start_if, stop_if, num_intervals):
    duration = length / num_intervals
    step = (stop_if - start_if) / (num_intervals-1)
    times = [duration] * num_intervals
    ifs = [start_if + step*i for i in range(num_intervals)]
    return [times, ifs]

In [89]:
def an_fo(num_intervals, t_if, r_if):
    times = [3] * num_intervals * 2
    ifs = [t_if, r_if] * num_intervals
    return [times, ifs]

In [91]:
def cool(duration, t_if):
    return [[duration/1.0], [t_if]]

In [72]:
def workout_summary(times, ifs):
    tss = 0
    t_if = 0
    duration = sum(times)/60
    for i in range(len(times)):
        tss += times[i] * ifs[i]**2
    tss *= (100/60)
    t_if = math.sqrt(tss / duration / 100)
    print("Workout Details")
    for i in range(len(times)):
        print("Interval {} - Duration: {:.2f}, IF: {:.2f}".format(i+1, times[i], ifs[i]))
    print("Workout Summary")
    print("Total TSS: {:.2f}, Average IF: {:.2f}".format(tss, t_if))
    #return tss, t_if

In [87]:
warmup = warmup(20, 0.5, 0.65, 4)

In [90]:
an_fo = an_fo(5, 1.1, 0.6)

In [92]:
cool = cool(40, 0.65)

In [116]:
workout = []
workout = np.append(warmup, an_fo, axis=1)
workout

array([[ 5.  ,  5.  ,  5.  ,  5.  ,  3.  ,  3.  ,  3.  ,  3.  ,  3.  ,
         3.  ,  3.  ,  3.  ,  3.  ,  3.  ],
       [ 0.5 ,  0.55,  0.6 ,  0.65,  1.1 ,  0.6 ,  1.1 ,  0.6 ,  1.1 ,
         0.6 ,  1.1 ,  0.6 ,  1.1 ,  0.6 ]])

In [118]:
workout = np.append(workout, cool, axis=1)
workout

array([[  5.  ,   5.  ,   5.  ,   5.  ,   3.  ,   3.  ,   3.  ,   3.  ,
          3.  ,   3.  ,   3.  ,   3.  ,   3.  ,   3.  ,  40.  ],
       [  0.5 ,   0.55,   0.6 ,   0.65,   1.1 ,   0.6 ,   1.1 ,   0.6 ,
          1.1 ,   0.6 ,   1.1 ,   0.6 ,   1.1 ,   0.6 ,   0.65]])

In [112]:
workout

array([[ 5.  ,  5.  ,  5.  ,  5.  ,  3.  ,  3.  ,  3.  ,  3.  ,  3.  ,
         3.  ,  3.  ,  3.  ,  3.  ,  3.  ],
       [ 0.5 ,  0.55,  0.6 ,  0.65,  1.1 ,  0.6 ,  1.1 ,  0.6 ,  1.1 ,
         0.6 ,  1.1 ,  0.6 ,  1.1 ,  0.6 ]])

In [95]:
cool

[[40.0], [0.65]]

In [97]:
workout = []
workout.extend(warmup)
workout

[[5.0, 5.0, 5.0, 5.0], [0.5, 0.55, 0.6, 0.65]]

In [98]:
workout.extend(an_fo)
workout

[[5.0, 5.0, 5.0, 5.0],
 [0.5, 0.55, 0.6, 0.65],
 [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
 [1.1, 0.6, 1.1, 0.6, 1.1, 0.6, 1.1, 0.6, 1.1, 0.6]]

In [77]:
times.extend(t)
ifs.extend(i)

In [79]:
times.extend(t)
ifs.extend(i)

In [84]:
workout_summary(times, ifs)

Workout Details
Interval 1 - Duration: 5.00, IF: 0.50
Interval 2 - Duration: 5.00, IF: 0.55
Interval 3 - Duration: 5.00, IF: 0.60
Interval 4 - Duration: 5.00, IF: 0.65
Interval 5 - Duration: 3.00, IF: 1.10
Interval 6 - Duration: 3.00, IF: 0.60
Interval 7 - Duration: 3.00, IF: 1.10
Interval 8 - Duration: 3.00, IF: 0.60
Interval 9 - Duration: 3.00, IF: 1.10
Interval 10 - Duration: 3.00, IF: 0.60
Interval 11 - Duration: 3.00, IF: 1.10
Interval 12 - Duration: 3.00, IF: 0.60
Interval 13 - Duration: 3.00, IF: 1.10
Interval 14 - Duration: 3.00, IF: 0.60
Interval 15 - Duration: 40.00, IF: 0.65
Workout Summary
Total TSS: 78.54, Average IF: 0.72


In [80]:
times

[5.0, 5.0, 5.0, 5.0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 40.0]

In [81]:
ifs

[0.5, 0.55, 0.6, 0.65, 1.1, 0.6, 1.1, 0.6, 1.1, 0.6, 1.1, 0.6, 1.1, 0.6, 0.65]

In [82]:
len(times)

15

In [83]:
len(ifs)

15

In [62]:
tss

78.54166666666667

In [63]:
t_if

0.7236097782030804